const menu = [
  {
    id: 1,
    title: "Breakfast Plates - with 2 Eggs, Hashbrown & Toast",
    category: "breakfast",
    img: "./images/item-1.jpeg",
    desc: "Breakfast Plate",
    subItems: [
      { name: "Classic", price: 7.69 },
      { name: "Bacon or Sausage", price: 9.99 },
      { name: "Ribeye Steak", price: 16.49 },
      { name: "Chicken Breast", price: 11.99 },
      { name: "Ham", price: 9.99 },
    ],
  },
  {
    id: 2,
    title:
      "Mexican Breakfast Plates - Served with 2 Eggs, Rice, Beans & Tortilla",
    category: "breakfast",
    img: "./images/item-2.jpeg",
    desc: "Mexican Breakfast Plate",
    subItems: [
      { name: "Chorizo", price: 9.99 },
      { name: "Huevos Rancheros", price: 10.39 },
      { name: "Chillaquiles", price: 10.39 },
    ],
  },
  {
    id: 3,
    title: "Omelettes - With 3 Eggs, Hashbrown & Toast",
    category: "breakfast",
    img: "./images/item-3.jpeg",
    desc: "Omelette",
    subItems: [
      { name: "Cheese", price: 9.89 },
      { name: "Denver (Bell Peppers & Onions)", price: 11.49 },
      { name: "Spanish (Potatoes & Onions)", price: 11.49 },
      { name: "Bacon or Sausage or Ham", price: 10.99 },
      { name: "Chili", price: 10.99 },
      { name: "Vegetarian", price: 10.99 },
    ],
  },
  {
    id: 4,
    title: "Breakfast Burritos - Made with 2 Eggs, Hashbrown, Pico & Cheese ",
    category: "breakfast",
    img: "./images/item-4.jpeg",
    desc: "Breakfast Burrito",
    subItems: [
      { name: "Egg", price: 6.59 },
      { name: "Bacon or Sausage", price: 8.69 },
      { name: "Ham", price: 8.69 },
      { name: "Chorizo", price: 9.79 },
      { name: "Combo (Bacon, Sausage, & Ham)", price: 10.29 },
    ],
  },
  {
    id: 5,
    title:
      "Breakfast Sandwiches - Made with 2 Eggs, Cheese, Mayo, Lettuce & Tomato",
    category: "breakfast",
    img: "./images/item-5.jpeg",
    desc: "Breakfast Sandwich",
    subItems: [
      { name: "Egg", price: 6.59 },
      { name: "Bacon or Sausage", price: 8.69 },
      { name: "Ham", price: 8.69 },
      { name: "Denver", price: 9.99 },
      { name: "Ribeye Steak", price: 15.99 },
    ],
  },
  {
    id: 6,
    title: "Hot Cakes (Pancake)",
    category: "breakfast",
    img: "./images/item-6.jpeg",
    desc: "Hot Cakes",
    subItems: [
      { name: "Bacon or Sausage (3) & 2 Eggs", price: 9.99 },
      { name: "Short Stack (2)", price: 5.99 },
      { name: "Full Stack (3)", price: 7.89 },
      { name: "Side Hot Cake", price: 3.29 },
      { name: "Chorizo", price: 9.99 },
    ],
  },
  {
    id: 7,
    title: "French Toast",
    category: "breakfast",
    img: "./images/item-7.jpeg",
    desc: "French Toast",
    subItems: [
      { name: "Bacon or Sausage (3) & 2 Eggs", price: 9.99 },
      { name: "4 Wedges", price: 5.99 },
      { name: "6 Wedges", price: 7.89 },
    ],
  },
  {
    id: 8,
    title: "Burgers - 1000 Island Dressing, Onion, Lettuce, Tomato & Pickle.",
    category: "lunch",
    img: "./images/item-8.jpeg",
    desc: "Burger",
    subItems: [
      { name: "Avocado Bacon Cheeseburger", price: 10.99 },
      { name: "Classic Hamburger", price: 5.29 },
      { name: "Double Cheeseburger", price: 8.39 },
      { name: "Chili Cheeseburger", price: 11.49 },
      { name: "Pastrami Burger", price: 10.99 },
      { name: "Mushroom Burger", price: 6.99 },
      { name: "Sourdough Burger", price: 7.09 },
    ],
  },
  {
    id: 9,
    title:
      "Specialty Platters - Choose 2 sides from rice, bean, fries, or salad. & choice of dinner roll or tortilla ",
    category: "lunch",
    img: "./images/item-9.jpeg",
    desc: "Platter",
    subItems: [
      { name: "Ribeye Steak", price: 15.99 },
      { name: "Chicken Breast", price: 12.19 },
      { name: "Carne Asada", price: 13.09 },
      { name: "Chicken Strips (4)", price: 8.79 },
      { name: "Fish & Chips", price: 10.39 },
      { name: "Asada Quesadilla", price: 13.09 },
      { name: "Taquitos", price: 6.99 },
    ],
  },
  {
    id: 16,
    title:
      "Teriyaki with Steamed White Rice & Cabbage. Comes with a choice of salad or fries. Add avocado for $1.79",
    category: "lunch",
    img: "./images/item-16.jpeg",
    desc: "Teriyaki",
    subItems: [
      { name: "Chicken", price: 11.49 },
      { name: "Beef", price: 12.99 },
      { name: "Chicken & Beef", price: 12.99 },
      { name: "Bulgogi - Korean Style Marinated", price: 13.99 },
      { name: "Vegetarian Teriyaki", price: 10.99 },
    ],
  },
  {
    id: 10,
    title:
      "Salads With Iceberg Lettuce, Cheese, Tomato, Cucumber, Egg & Crouton",
    category: "lunch",
    img: "./images/item-10.jpeg",
    desc: "Salad",
    subItems: [
      { name: "Green Salad", price: 6.89 },
      { name: "Chef or Tuna Salad", price: 10.99 },
      { name: "Grilled Chicken Breast", price: 10.99 },
    ],
  },
  {
    id: 11,
    title: "Sandwiches",
    category: "lunch",
    img: "./images/item-11.jpeg",
    desc: "Sandwich",
    subItems: [
      { name: "Ribeye Steak", price: 14.59 },
      { name: "Famous Pastrami", price: 13.59 },
      { name: "Club", price: 9.99 },
      { name: "Avocado Turkey BLT", price: 10.19 },
      { name: "Chicken Melt", price: 10.69 },
      { name: "Parmesan Grilled Chicken", price: 13.59 },
      { name: "Tuna Melt", price: 8.99 },
    ],
  },
  {
    id: 12,
    title: "Philly Cheesesteak - Mayo, Grilled Onions, & Swiss Cheese",
    category: "lunch",
    img: "./images/item-12.jpeg",
    desc: "Philly Cheesesteak",
    subItems: [
      { name: "Cheese Steak", price: 10.79 },
      { name: "Bell Pepper or Mushroom Steak", price: 11.29 },
    ],
  },

  {
    id: 14,
    title: "South of the Border",
    category: "lunch",
    img: "./images/item-14.jpeg",
    desc: "South of the Border",
    subItems: [
      { name: "Carne Asada Burrito", price: 10.29 },
      { name: "California Burrito (Beans, Fries, Avocado)", price: 10.79 },
      { name: "Chicken Quesadilla", price: 9.79 },
      { name: "Asada Super Nachos", price: 13.59 },
      { name: "Chicken Torta", price: 10.79 },
      { name: "BRC Burrito", price: 8.09 },
      { name: "Taquitos (3)", price: 3.89 },
      { name: "Cheesy Nacho Fries", price: 6.89 },
    ],
  },
  {
    id: 15,
    title: "Taco Combo Special - 2 Tacos, Rice, Beans & Drink",
    category: "lunch",
    img: "./images/item-15.jpeg",
    desc: "Taco Combo",
    subItems: [
      { name: "Carne Asada", price: 12.89 },
      { name: "Chicken or Fish", price: 11.89 },
    ],
  },

  {
    id: 17,
    title: "Breakfast Side Orders",
    category: "sides",
    img: "./images/item-17.jpeg",
    desc: "Side",
    subItems: [
      { name: "Hash Brown", price: 3.59 },
      { name: "Toast", price: 1.89 },
      { name: "Egg (1)", price: 1.59 },
      { name: "Bacon or Sausage (2)", price: 2.49 },
      { name: "Ham", price: 2.49 },
    ],
  },

  {
    id: 18,
    title: "Fresh Side Orders",
    category: "sides",
    img: "./images/item-18.jpeg",
    desc: "Side",
    subItems: [
      { name: "French Fries", price: 3.59 },
      { name: "Chili Cheese Fries", price: 7.79 },
      { name: "Bowl of Chili", price: 4.79 },
      { name: "Rice or Beans", price: 2.0 },
      { name: "Chicken Strips (3)", price: 5.79 },
      { name: "Cheese Sticks (6)", price: 4.59 },
      { name: "Avocado", price: 1.79 },
      { name: "Guacamole", price: 0.8 },
      { name: "Sour Cream", price: 0.8 },
      { name: "Mushroom or Bell Pepper", price: 1.0 },
    ],
  },
{
    id: 13,
    title: "Hot Dogs",
    category: "lunch",
    img: "./images/item-13.jpeg",
    subItems: [
      { name: "Hot Dog", price: 4.99 },
      { name: "Chili Cheese Dog", price: 6.09 },
      { name: "Bacon Dog", price: 6.09 },
    ],
  },
  {
    id: 19,
    title: "Drinks",
    category: "drinks",
    img: "./images/item-19.jpeg",
    desc: "Drinks",
    subItems: [
      { name: "Fountain Drink", price: 3.79 },
      { name: "Small Coffee", price: 1.99 },
      { name: "Large Coffee", price: 2.49 },
      { name: "Bottled Water", price: 1.79 },
      { name: "Hot Green Tea", price: 1.99 },
      { name: "Milk", price: 2.69 },
      { name: "Orange Juice", price: 2.69 },
      { name: "Gatorade", price: 2.69 },
      { name: "Arizona Tea", price: 2.69 },
      { name: "Canned Sona", price: 1.85 },
    ],
  },
];
export default menu;
